
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.proc-macro2]]
version = "1.0.106"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.44"
criteria = "safe-to-deploy"

[[exemptions.serde]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_core]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.serde_derive]]
version = "1.0.228"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.114"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.23"
criteria = "safe-to-deploy"
